// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gophkeeper_securedata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecureDataServiceClient is the client API for SecureDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecureDataServiceClient interface {
	AddSecureData(ctx context.Context, in *AddSecureDataRequest, opts ...grpc.CallOption) (*AddSecureDataResponse, error)
	GetSecureData(ctx context.Context, in *GetSecureDataRequest, opts ...grpc.CallOption) (*GetSecureDataResponse, error)
	DeleteSecureData(ctx context.Context, in *DeleteSecureDataRequest, opts ...grpc.CallOption) (*DeleteSecureDataResponse, error)
	SyncSecureData(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (SecureDataService_SyncSecureDataClient, error)
}

type secureDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecureDataServiceClient(cc grpc.ClientConnInterface) SecureDataServiceClient {
	return &secureDataServiceClient{cc}
}

func (c *secureDataServiceClient) AddSecureData(ctx context.Context, in *AddSecureDataRequest, opts ...grpc.CallOption) (*AddSecureDataResponse, error) {
	out := new(AddSecureDataResponse)
	err := c.cc.Invoke(ctx, "/gophkeeper_securedata.SecureDataService/AddSecureData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureDataServiceClient) GetSecureData(ctx context.Context, in *GetSecureDataRequest, opts ...grpc.CallOption) (*GetSecureDataResponse, error) {
	out := new(GetSecureDataResponse)
	err := c.cc.Invoke(ctx, "/gophkeeper_securedata.SecureDataService/GetSecureData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureDataServiceClient) DeleteSecureData(ctx context.Context, in *DeleteSecureDataRequest, opts ...grpc.CallOption) (*DeleteSecureDataResponse, error) {
	out := new(DeleteSecureDataResponse)
	err := c.cc.Invoke(ctx, "/gophkeeper_securedata.SecureDataService/DeleteSecureData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureDataServiceClient) SyncSecureData(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (SecureDataService_SyncSecureDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &SecureDataService_ServiceDesc.Streams[0], "/gophkeeper_securedata.SecureDataService/SyncSecureData", opts...)
	if err != nil {
		return nil, err
	}
	x := &secureDataServiceSyncSecureDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SecureDataService_SyncSecureDataClient interface {
	Recv() (*SyncResponse, error)
	grpc.ClientStream
}

type secureDataServiceSyncSecureDataClient struct {
	grpc.ClientStream
}

func (x *secureDataServiceSyncSecureDataClient) Recv() (*SyncResponse, error) {
	m := new(SyncResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SecureDataServiceServer is the server API for SecureDataService service.
// All implementations must embed UnimplementedSecureDataServiceServer
// for forward compatibility
type SecureDataServiceServer interface {
	AddSecureData(context.Context, *AddSecureDataRequest) (*AddSecureDataResponse, error)
	GetSecureData(context.Context, *GetSecureDataRequest) (*GetSecureDataResponse, error)
	DeleteSecureData(context.Context, *DeleteSecureDataRequest) (*DeleteSecureDataResponse, error)
	SyncSecureData(*SyncRequest, SecureDataService_SyncSecureDataServer) error
	mustEmbedUnimplementedSecureDataServiceServer()
}

// UnimplementedSecureDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSecureDataServiceServer struct {
}

func (UnimplementedSecureDataServiceServer) AddSecureData(context.Context, *AddSecureDataRequest) (*AddSecureDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSecureData not implemented")
}
func (UnimplementedSecureDataServiceServer) GetSecureData(context.Context, *GetSecureDataRequest) (*GetSecureDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecureData not implemented")
}
func (UnimplementedSecureDataServiceServer) DeleteSecureData(context.Context, *DeleteSecureDataRequest) (*DeleteSecureDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSecureData not implemented")
}
func (UnimplementedSecureDataServiceServer) SyncSecureData(*SyncRequest, SecureDataService_SyncSecureDataServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncSecureData not implemented")
}
func (UnimplementedSecureDataServiceServer) mustEmbedUnimplementedSecureDataServiceServer() {}

// UnsafeSecureDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecureDataServiceServer will
// result in compilation errors.
type UnsafeSecureDataServiceServer interface {
	mustEmbedUnimplementedSecureDataServiceServer()
}

func RegisterSecureDataServiceServer(s grpc.ServiceRegistrar, srv SecureDataServiceServer) {
	s.RegisterService(&SecureDataService_ServiceDesc, srv)
}

func _SecureDataService_AddSecureData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSecureDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureDataServiceServer).AddSecureData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gophkeeper_securedata.SecureDataService/AddSecureData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureDataServiceServer).AddSecureData(ctx, req.(*AddSecureDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureDataService_GetSecureData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecureDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureDataServiceServer).GetSecureData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gophkeeper_securedata.SecureDataService/GetSecureData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureDataServiceServer).GetSecureData(ctx, req.(*GetSecureDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureDataService_DeleteSecureData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecureDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureDataServiceServer).DeleteSecureData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gophkeeper_securedata.SecureDataService/DeleteSecureData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureDataServiceServer).DeleteSecureData(ctx, req.(*DeleteSecureDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureDataService_SyncSecureData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecureDataServiceServer).SyncSecureData(m, &secureDataServiceSyncSecureDataServer{stream})
}

type SecureDataService_SyncSecureDataServer interface {
	Send(*SyncResponse) error
	grpc.ServerStream
}

type secureDataServiceSyncSecureDataServer struct {
	grpc.ServerStream
}

func (x *secureDataServiceSyncSecureDataServer) Send(m *SyncResponse) error {
	return x.ServerStream.SendMsg(m)
}

// SecureDataService_ServiceDesc is the grpc.ServiceDesc for SecureDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecureDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeeper_securedata.SecureDataService",
	HandlerType: (*SecureDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSecureData",
			Handler:    _SecureDataService_AddSecureData_Handler,
		},
		{
			MethodName: "GetSecureData",
			Handler:    _SecureDataService_GetSecureData_Handler,
		},
		{
			MethodName: "DeleteSecureData",
			Handler:    _SecureDataService_DeleteSecureData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncSecureData",
			Handler:       _SecureDataService_SyncSecureData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "secure_data.proto",
}
