syntax = "proto3";

package gophkeeper_password;

service PasswordService {
  rpc AddPassword(AddPasswordRequest) returns (AddPasswordResponse);
  rpc GetPassword(GetPasswordRequest) returns (GetPasswordResponse);
  rpc DeletePassword(DeletePasswordRequest) returns (DeletePasswordResponse);
  rpc SyncPasswords(SyncRequest) returns (stream SyncResponse);
}

message AddPasswordRequest {
  string token = 1;
  string site = 2;
  string login = 3;
  string password = 4;
  string meta_info = 5;
}

message AddPasswordResponse { string message = 1; }

message GetPasswordRequest { string token = 1; string site = 2; }

message GetPasswordResponse {
  string login = 1;
  string password = 2;
  string meta_info = 3;
}

message DeletePasswordRequest { string token = 1; string site = 2; }
message DeletePasswordResponse { string message = 1; }

message SyncRequest { string token = 1; }

message SyncResponse {
  string site = 1;
  string login = 2;
  string password = 3;
  string meta_info = 4;
  string action = 5;
}
